# -*- coding: utf-8 -*-
"""SK1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ON7XcOK5f0LgRPFyZ5GYR4iPZT_n3cbp
"""

import sklearn

from sklearn.datasets import load_iris

load_iris()

load_iris(return_X_y=True)

X,y = load_iris(return_X_y=True) #feature in x and output in y

from sklearn.linear_model import LinearRegression

Model = LinearRegression()

Model.fit(X,y)

Model.predict(X)

from sklearn.neighbors import KNeighborsClassifier
mod = KNeighborsClassifier()

mod.fit(X,y)

mod.predict(X)

import matplotlib.pyplot as plt
pred = mod.predict(X)

plt.scatter(pred,y)

import pandas as pd

from sklearn.datasets import fetch_openml

df = fetch_openml('titanic',version =1,as_frame=True)['data']

df.info()

